apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: master-ibm-sea
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
        - path: /etc/sysctl.d/99-sysctl-pmtu-sea.conf
          overwrite: true
          mode: 0644
          filesystem: root
          contents:
            source: data:text/plain;charset=utf-8;base64,bmV0LmlwdjQuaXBfbm9fcG10dV9kaXNjID0gMQpuZXQuaXB2NC5yb3V0ZS5taW5fcG10dT0xNDUwCg==
