---
- name: Collect MAC address from LPAR
  hosts: localhost
  gather_facts: no
  collections:
      - ibm.power_hmc

  connection: local
  become: false

  vars_files:
    - ../vars/hmcs.yml
    - ../vars/lpars.yml
    - ../vars/nodes.yml

  vars:
    mac_address: {}

  tasks:
  - name: Boot LPARs for MAC discovery
    hmc_command:
      hmc_host: "{{ hmc[lpars[item['lpar_name']].hmc].ip }}"
      hmc_auth: "{{ hmc[lpars[item['lpar_name']].hmc].hmc_auth }}"
      cmd: >
          lpar_netboot -M -n -f -t ent
          {{ item['lpar_name'] }}
          {{ lpars[item['lpar_name']].profile | default('default_profile') }}
          {{ lpars[item['lpar_name']].managed_system }}
    loop: "{{ bootnode + masters + workers | default([]) }}"
    register: lpar_data

  - name: Register MAC address
    set_fact:
      mac_address: "{{ mac_address | combine({item['item']['lpar_name']: item.command_output[-1].split(' ')[2] | ansible.utils.hwaddr('linux')} ) }}"
    loop: "{{ lpar_data.results }}"

  - name: Show MAC addresses
    debug:
      msg: "{{ mac_address }}"
